name: LiveSkin
description: "ИИ-система, превращающая одежду в инструмент работы с телом и психикой"
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  camera: ^0.10.5+9
  image: ^4.1.7
  google_ml_kit: ^0.20.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
